### PR TITLE
Update the initialisation of init_state and learned_ema_beta to match…

### PR DESCRIPTION
**Pull request by psoulos**
… the original repo

### CODE REVIEW

**Comment by lucidrains** [comment]
thank you!

**Comment by lucidrains** [comment]
@psoulos are you using this for some research?

**Comment by psoulos** [comment]
@lucidrains yes! We are using the block recurrent transformer as a baseline to compare against some other models.

**Comment by lucidrains** [comment]
@psoulos that's awesome, was hoping the repo would be useful to somebody

**Comment by psoulos** [comment]
@lucidrains The repo was incredibly useful, thank you so much for your contributions to open science! I will follow up here once we have a preprint in case you are interested in our results.

**Comment by lucidrains** [comment]
@psoulos please do!

**Pull request merged**
